// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOrQIY4wnAXX2ypLduF4UT8UfYmMEmTEk',
    appId: '1:30076380522:web:e0fba7b912897d79527113',
    messagingSenderId: '30076380522',
    projectId: 'fit-rope-app-1f575',
    authDomain: 'fit-rope-app-1f575.firebaseapp.com',
    storageBucket: 'fit-rope-app-1f575.firebasestorage.app',
    measurementId: 'G-W4L2DF3W18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP08HValdX6C44no-4WdgYtWFuOGpq2Gw',
    appId: '1:30076380522:android:8750e72642dc627c527113',
    messagingSenderId: '30076380522',
    projectId: 'fit-rope-app-1f575',
    storageBucket: 'fit-rope-app-1f575.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGICQtiN-FdUvOf4QkrWWfT2TV-zf0g0I',
    appId: '1:30076380522:ios:33ccf875babe2867527113',
    messagingSenderId: '30076380522',
    projectId: 'fit-rope-app-1f575',
    storageBucket: 'fit-rope-app-1f575.firebasestorage.app',
    iosBundleId: 'com.example.fitropeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGICQtiN-FdUvOf4QkrWWfT2TV-zf0g0I',
    appId: '1:30076380522:ios:33ccf875babe2867527113',
    messagingSenderId: '30076380522',
    projectId: 'fit-rope-app-1f575',
    storageBucket: 'fit-rope-app-1f575.firebasestorage.app',
    iosBundleId: 'com.example.fitropeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOrQIY4wnAXX2ypLduF4UT8UfYmMEmTEk',
    appId: '1:30076380522:web:9bd9c884c8d1c0dc527113',
    messagingSenderId: '30076380522',
    projectId: 'fit-rope-app-1f575',
    authDomain: 'fit-rope-app-1f575.firebaseapp.com',
    storageBucket: 'fit-rope-app-1f575.firebasestorage.app',
    measurementId: 'G-GJN354H53F',
  );
}
