name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
        
      - name: Run tests
        run: flutter test
        
      - name: Run analysis
        run: flutter analyze
        
      - name: Check formatting
        run: flutter format --set-exit-if-changed .
        
      - name: Build for all platforms (dry run)
        run: |
          flutter build apk --debug
          flutter build ios --debug --no-codesign
          flutter build web --debug 