name: Release Build & Deploy

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
        
      - name: Run tests
        run: flutter test
        
      - name: Run analysis
        run: flutter analyze || true

  # build-android:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
      
  #     - name: Setup Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: '3.24.0'
  #         channel: 'stable'
      
  #     - name: Install dependencies
  #       run: flutter pub get
        
  #     - name: Build APK
  #       run: flutter build apk --release
        
  #     - name: Upload APK
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: fitrope-app-release
  #         path: build/app/outputs/flutter-apk/app-release.apk

  # build-ios:
  #   needs: test
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v4
      
  #     - name: Setup Flutter
  #       uses: subosito/flutter-action@v2
  #         flutter-version: '3.24.0'
  #         channel: 'stable'
      
  #     - name: Install dependencies
  #       run: flutter pub get
        
  #     - name: Build iOS
  #       run: flutter build ios --release --no-codesign
        
  #     - name: Upload iOS build
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: fitrope-ios-release
  #         path: build/ios/iphoneos/Runner.app

  build-web:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.21.0
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build Web
        run: flutter build web --release
        
      - name: Upload Web build
        uses: actions/upload-artifact@v4.6.2
        with:
          name: fitrope-web-release
          path: build/web

  deploy:
    needs: [build-web]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'
    steps:
      - name: Download web artifact
        uses: actions/download-artifact@v4.3.0
        with:
          name: fitrope-web-release
          path: ./web-build
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web-build
          publish_branch: release
          force_orphan: true
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          body: |
            ## FitRope App Release v${{ github.run_number }}
            
            ### Builds disponibili:
            - **Android APK**: Scarica l'APK dalla sezione Assets
            - **iOS**: Build disponibile per distribuzione
            - **Web**: Disponibile su [GitHub Pages](https://fgrotta.github.io/fitrope_app/)
            
            ### Changelog:
            - Build automatica dal branch release
            - Test e analisi del codice completati
            - Build multi-piattaforma
            - Deployment automatico su GitHub Pages
            
          draft: false
          prerelease: false
          
      # - name: Upload APK to Release
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./fitrope-app-release/app-release.apk
      #     asset_name: fitrope-app-release.apk
      #     asset_content_type: application/vnd.android.package-archive 